### PR TITLE
Create CODEOWNERS

### PR DESCRIPTION
**Pull request by dslomov**
Adding all GitHub repo admins as global CODEOWNERS

### CODE REVIEW

**Comment by dslomov** [comment]
Folks tell me if this is the right set of people.

**Comment by dkelmer** [comment]
I would assume that dj should be a code owner (and admin). And I don't think I should be either.

**Comment by ahumesky** [comment]
yeah, what dkelmer said

**Comment by dslomov** [comment]
> I would assume that dj should be a code owner (and admin). And I don't think I should be either.

Do you mean @jin ?

**Comment by jin** [comment]
It's @djwhang

**Comment by dslomov** [comment]
please take another look

**Comment by dslomov** [comment]
Is it ok to just merge?

**Pull request merged**
